### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/ssl/key.pem'

### ISSUE THREAD

**Issue by sraza295** [Dirvann/mediasoup-sfu-webrtc-video-rooms#1]
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/ssl/key.pem'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:363:35)
    at Object.<anonymous> (/home/shahnawaz/Downloads/mediasoup-sfu-webrtc-video-rooms-master/src/app.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/ssl/key.pem'
}
[nodemon] app crashed - waiting for file changes before starting...

I am getting this error.
I am attaching the screenshot of project structure
![Screenshot from 2020-08-04 14-26-44](https://user-images.githubusercontent.com/37663062/89274615-ce9eb980-d65e-11ea-8888-9f3660fd7ffe.png)
![Screenshot from 2020-08-04 14-29-06](https://user-images.githubusercontent.com/37663062/89274672-deb69900-d65e-11ea-86b1-cd6f0e814c5c.png)

. Kindly check it.

**Comment by Dirvann** [comment]
Thank you for the comment. 
The issue got fixed in https://github.com/Dirvann/mediasoup-sfu-webrtc-video-rooms/commit/a8c45fe5b1fb30e483a1a73d7917683a0a4684e6.

**Comment by sraza295** [comment]
Is this project SFU simulcast?

**Comment by Dirvann** [comment]
Yes it is
