### ISSUE TITLE
Application that crashes after 7-10 days, it's done it twice

### ISSUE THREAD

**Issue by Madriix** [Dirvann/mediasoup-sfu-webrtc-video-rooms#21]
Here is the pm2 log:

```
Consume failed TypeError: Cannot read properties of undefined (reading 'consume')
    at Peer.createConsumer (/home/debian/node/appname/mediasoup/src/Peer.js:48:42)
    at Room.consume (/home/debian/node/appname/mediasoup/src/Room.js:118:8)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:190:53)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/home/debian/node/appname/mediasoup/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/debian/node/appname/mediasoup/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
TypeError: Cannot destructure property 'consumer' of '(intermediate value)' as it is undefined.
    at Room.consume (/home/debian/node/appname/mediasoup/src/Room.js:116:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:190:18)
Consume failed TypeError: Cannot read properties of undefined (reading 'consume')
    at Peer.createConsumer (/home/debian/node/appname/mediasoup/src/Peer.js:48:42)
    at Room.consume (/home/debian/node/appname/mediasoup/src/Room.js:118:8)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:190:53)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/home/debian/node/appname/mediasoup/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/debian/node/appname/mediasoup/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
TypeError: Cannot destructure property 'consumer' of '(intermediate value)' as it is undefined.
    at Room.consume (/home/debian/node/appname/mediasoup/src/Room.js:116:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:190:18)
Consume failed TypeError: Cannot read properties of undefined (reading 'consume')
    at Peer.createConsumer (/home/debian/node/appname/mediasoup/src/Peer.js:48:42)
    at Room.consume (/home/debian/node/appname/mediasoup/src/Room.js:118:8)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:190:53)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/home/debian/node/appname/mediasoup/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/debian/node/appname/mediasoup/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
TypeError: Cannot destructure property 'consumer' of '(intermediate value)' as it is undefined.
    at Room.consume (/home/debian/node/appname/mediasoup/src/Room.js:116:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:190:18)
can not consume
TypeError: Cannot read properties of undefined (reading 'id')
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:195:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'produce')
    at Peer.createProducer (/home/debian/node/appname/mediasoup/src/Peer.js:24:66)
    at Room.<anonymous> (/home/debian/node/appname/mediasoup/src/Room.js:92:56)
    at new Promise (<anonymous>)
    at Room.produce (/home/debian/node/appname/mediasoup/src/Room.js:90:12)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:175:58)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/home/debian/node/appname/mediasoup/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/debian/node/appname/mediasoup/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
TypeError: Cannot read properties of undefined (reading 'close')
    at Peer.closeProducer (/home/debian/node/appname/mediasoup/src/Peer.js:90:38)
    at Room.closeProducer (/home/debian/node/appname/mediasoup/src/Room.js:144:31)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:224:34)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/home/debian/node/appname/mediasoup/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/debian/node/appname/mediasoup/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
TypeError: Cannot read properties of undefined (reading 'produce')
    at Peer.createProducer (/home/debian/node/appname/mediasoup/src/Peer.js:24:66)
    at Room.<anonymous> (/home/debian/node/appname/mediasoup/src/Room.js:92:56)
    at new Promise (<anonymous>)
    at Room.produce (/home/debian/node/appname/mediasoup/src/Room.js:90:12)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:175:58)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/home/debian/node/appname/mediasoup/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/debian/node/appname/mediasoup/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Consume failed TypeError: Cannot read properties of undefined (reading 'consume')
    at Peer.createConsumer (/home/debian/node/appname/mediasoup/src/Peer.js:48:42)
    at Room.consume (/home/debian/node/appname/mediasoup/src/Room.js:118:8)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:190:53)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/home/debian/node/appname/mediasoup/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/debian/node/appname/mediasoup/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
TypeError: Cannot destructure property 'consumer' of '(intermediate value)' as it is undefined.
    at Room.consume (/home/debian/node/appname/mediasoup/src/Room.js:116:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:190:18)
Consume failed TypeError: Cannot read properties of undefined (reading 'consume')
    at Peer.createConsumer (/home/debian/node/appname/mediasoup/src/Peer.js:48:42)
    at Room.consume (/home/debian/node/appname/mediasoup/src/Room.js:118:8)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:190:53)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/home/debian/node/appname/mediasoup/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/debian/node/appname/mediasoup/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
TypeError: Cannot destructure property 'consumer' of '(intermediate value)' as it is undefined.
    at Room.consume (/home/debian/node/appname/mediasoup/src/Room.js:116:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:190:18)
can not consume
TypeError: Cannot read properties of undefined (reading 'id')
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:195:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
can not consume
TypeError: Cannot read properties of undefined (reading 'id')
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:195:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'close')
    at Peer.closeProducer (/home/debian/node/appname/mediasoup/src/Peer.js:90:38)
    at Room.closeProducer (/home/debian/node/appname/mediasoup/src/Room.js:144:31)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:224:34)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/home/debian/node/appname/mediasoup/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/debian/node/appname/mediasoup/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Consume failed TypeError: Cannot read properties of undefined (reading 'consume')
    at Peer.createConsumer (/home/debian/node/appname/mediasoup/src/Peer.js:48:42)
    at Room.consume (/home/debian/node/appname/mediasoup/src/Room.js:118:8)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:190:53)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/home/debian/node/appname/mediasoup/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/debian/node/appname/mediasoup/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
TypeError: Cannot destructure property 'consumer' of '(intermediate value)' as it is undefined.
    at Room.consume (/home/debian/node/appname/mediasoup/src/Room.js:116:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:190:18)
TypeError: Cannot read properties of undefined (reading 'produce')
    at Peer.createProducer (/home/debian/node/appname/mediasoup/src/Peer.js:24:66)
    at Room.<anonymous> (/home/debian/node/appname/mediasoup/src/Room.js:92:56)
    at new Promise (<anonymous>)
    at Room.produce (/home/debian/node/appname/mediasoup/src/Room.js:90:12)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/src/app.js:175:58)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/home/debian/node/appname/mediasoup/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/debian/node/appname/mediasoup/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Error: no more available ports [transport:udp, ip:'51.255.xx.xx', numAttempt:10000] [method:router.createWebRtcTransport]
    at Channel.processMessage (/home/debian/node/appname/mediasoup/node_modules/mediasoup/node/lib/Channel.js:195:37)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/node_modules/mediasoup/node/lib/Channel.js:69:34)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
Error: no more available ports [transport:udp, ip:'51.255.xxxx', numAttempt:10000] [method:router.createWebRtcTransport]
    at Channel.processMessage (/home/debian/node/appname/mediasoup/node_modules/mediasoup/node/lib/Channel.js:195:37)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/node_modules/mediasoup/node/lib/Channel.js:69:34)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
Error: no more available ports [transport:udp, ip:'51.255.xx.xx', numAttempt:10000] [method:router.createWebRtcTransport]
    at Channel.processMessage (/home/debian/node/appname/mediasoup/node_modules/mediasoup/node/lib/Channel.js:195:37)
    at Socket.<anonymous> (/home/debian/node/appname/mediasoup/node_modules/mediasoup/node/lib/Channel.js:69:34)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

The log file is very large, but it still has the same identical errors

Where could the problem come from?

Here are the versions of my packages:
```
   "dependencies": {
     "express": "^4.17.1",
     "httppolyglot": "^0.1.2",
     "mediasoup": "^3.8.2",
     "mediasoup-client": "^3.6.37",
     "socket.io": "^4.1.3"
   }

```
cordially

**Comment by Madriix** [comment]
Hi

`numAttempt:10000`

What does that mean exactly?
Is this a port?

**Comment by Dirvann** [comment]
I see all your ports are apparently in use. Check in the config.js the rtcMinPort and rtcMaxPort. And change those values to ports that are definitely not in use on your PC

**Comment by Madriix** [comment]
Hi @Dirvann 

Here is the config.js:

```
      rtcMinPort: 20000,
      rtcMaxPort: 29999
```

Oh actually `numAttempt:10000` is it the calculation between 20,000 and 29,000? if for example I put `rtcMinPort: 10000 - rtcMaxPort: 29999` then it would display `numAttempt:20000` ?


In config.js I also commented :
```
          /*parameters: {
            'x-google-start-bitrate': 1000
          }*/

    // WebRtcTransport settings
    webRtcTransport: {
      listenIps: [
        {
          ip: '0.0.0.0',
          announcedIp: '<51.12.<ip_server>'
        }
      ],
      /*maxIncomingBitrate: 1500000,
      initialAvailableOutgoingBitrate: 1000000*/

```

Here is the list of open ports:

```
debian@ns:~$ sudo ufw status numbered
[ 1] 80                         ALLOW IN    Anywhere
[ 2] 443                        ALLOW IN    Anywhere
[ 3] 53                         ALLOW IN    Anywhere
[ 4] Nginx Full                 ALLOW IN    Anywhere
[ 5] Bind9                      ALLOW IN    Anywhere
[ 6] SSH                        ALLOW IN    Anywhere
[ 7] 10000  (for Webmin)                    ALLOW IN    Anywhere
[ 8] DNS                        ALLOW IN    Anywhere
[ 9] 1999                       ALLOW IN    Anywhere
[10] 20000:29999/tcp            ALLOW IN    Anywhere
[11] 20000:29999/udp            ALLOW IN    Anywhere
[12] 80 (v6)                    ALLOW IN    Anywhere (v6)
[13] 443 (v6)                   ALLOW IN    Anywhere (v6)
[14] 53 (v6)                    ALLOW IN    Anywhere (v6)
[15] Nginx Full (v6)            ALLOW IN    Anywhere (v6)
[16] Bind9 (v6)                 ALLOW IN    Anywhere (v6)
[17] SSH (v6)                   ALLOW IN    Anywhere (v6)
[18] 10000 (v6)   (for Webmin)                 ALLOW IN    Anywhere (v6)
[19] DNS (v6)                   ALLOW IN    Anywhere (v6)
[20] 1999 (v6)                  ALLOW IN    Anywhere (v6)
[21] 20000:29999/tcp (v6)       ALLOW IN    Anywhere (v6)
[22] 20000:29999/udp (v6)       ALLOW IN    Anywhere (v6)

```


> I see all your ports are apparently in use.

Are all ports between 20000 and 29999 in use?

Is there a system that closes each port automatically?

**Comment by rezahabibijan** [comment]
define a wider range of ports , for example from 10,000 up to 60,000
