### ISSUE TITLE
An error is caused and in 2 js files there is a note marked "TODO handle null errors",

### ISSUE THREAD

**Issue by Madriix** [Dirvann/mediasoup-sfu-webrtc-video-rooms#29]
An error is caused and in 2 js files there is a note marked "TODO handle null errors" and this error occurs.

First here is the error when I launch for example my microphone or camera:

```
/home/debian/node/dcs/mediasoup/src/Peer.js:24
    let producer = await this.transports.get(producerTransportId).produce({
                                                                 ^

TypeError: Cannot read properties of undefined (reading 'produce')
    at Peer.createProducer (/home/debian/node/dcs/mediasoup/src/Peer.js:24:66)
    at Room.<anonymous> (/home/debian/node/dcs/mediasoup/src/Room.js:92:56)
    at new Promise (<anonymous>)
    at Room.produce (/home/debian/node/dcs/mediasoup/src/Room.js:90:12)
    at Socket.<anonymous> (/home/debian/node/dcs/mediasoup/src/app.js:175:58)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (/home/debian/node/dcs/mediasoup/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/debian/node/dcs/mediasoup/node_modules/socket.io/dist/socket.js:614:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.12.1
```

I think the error occurs with the 2 comments there are here whose note is "TODO":

- https://github.com/Dirvann/mediasoup-sfu-webrtc-video-rooms/blob/6446c24dbbb47842e0a8d6e5f2404120e11fadfc/src/app.js#L179
- https://github.com/Dirvann/mediasoup-sfu-webrtc-video-rooms/blob/6446c24dbbb47842e0a8d6e5f2404120e11fadfc/src/Peer.js#L23

Does anyone have an idea how to fix/make them?

**Comment by miroslavpejic85** [comment]
> TypeError: Cannot read properties of undefined (reading 'produce')

You can **Check if the Transport Exists Before Calling `.produce()`**
Modify your `createProducer` function in `Peer.js`:
```js
let transport = this.transports.get(producerTransportId);
if (!transport) {
    console.error(`Transport with ID ${producerTransportId} not found`);
    return; // Or handle the error appropriately
}
let producer = await transport.produce({ ... });
```
This will prevent the error and help debug the missing transport.
